{
    'name': 'Event Management System',
    'version': '18.0.1.0',
    'category': 'Services',
    'summary': 'Event booking and hall management',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/event_type_views.xml',
        'views/amenity_views.xml',
        'views/hall_views.xml',
        'views/dish_category_views.xml',
        'views/menu_dishes_views.xml',
        'views/menu_meal_views.xml',
        # 'views/booking_views.xml',
        'views/booking_enhanced_views.xml',
        'views/menu_views.xml',
        'reports/booking_report.xml',
        # 'data/menu_dishes_demo.xml',
        # 'data/menu_meal_demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'event_management/static/src/css/booking_form.css',
            'event_management/static/src/css/hall.css',
            'event_management/static/src/css/menu_dishes.css',
            'event_management/static/src/css/menu_meal.css',
            'event_management/static/src/js/booking_form.js',
            'event_management/static/src/js/meal_selection_widget.js',
            'event_management/static/src/xml/meal_selection_widget.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}